"""Korean display titles for learner scenarios, keyed by stable scenario id."""

from __future__ import annotations

SCENARIO_TITLES_KO = {
    "lab01.default": "자동 데모",
    "lab01.underdamped": "저감쇠",
    "lab01.over-damped": "과감쇠",
    "lab01.high-stiffness": "높은 강성",
    "lab01.low-stiffness": "낮은 강성",
    "lab01.interactive-pull": "직접 조작",
    "lab01.f2-launch-high-energy": "실패 F2: 저장 에너지 발사",
    "lab01.f2-launch-precheck": "실패 F2: 안전한 대응",
    "lab02.default": "자동 데모",
    "lab02.p-low-gain": "낮은 P 게인",
    "lab02.p-high-gain": "높은 P 게인",
    "lab02.pd-damped": "PD 감쇠",
    "lab02.saturation-limit": "출력 포화",
    "lab02.pid-with-windup": "적분 와인드업",
    "lab02.pid-anti-windup": "안티 와인드업",
    "lab02.measurement-noise": "센서 잡음",
    "lab02.control-delay": "제어 지연",
    "lab02.interactive-disturbance": "직접 PID 튜닝",
    "lab03.joint-space-2dof": "2DOF 관절공간 제어",
    "lab03.task-space-2dof": "2DOF 작업공간 제어",
    "lab03.singularity-2dof": "2DOF 특이점",
    "lab03.dls-singularity-2dof": "2DOF DLS 특이점",
    "lab03.condition-aware-dls-2dof": "조건수 기반 DLS",
    "lab03.condition-aware-dls-early-2dof": "이른 DLS 감쇠",
    "lab03.condition-aware-dls-late-2dof": "늦은 DLS 감쇠",
    "lab03.condition-aware-dls-inner-target-2dof": "안쪽 목표 DLS",
    "lab03.condition-aware-dls-edge-target-2dof": "가장자리 목표 DLS",
    "lab03.condition-aware-dls-upper-path-2dof": "위쪽 경로 DLS",
    "lab03.condition-aware-dls-lower-path-2dof": "아래쪽 경로 DLS",
    "lab03.condition-aware-dls-shoulder-disturbance-2dof": "어깨 외란 DLS",
    "lab03.condition-aware-dls-elbow-disturbance-2dof": "팔꿈치 외란 DLS",
    "lab03.condition-aware-dls-staggered-disturbance-2dof": "순차 외란 DLS",
    "lab03.condition-aware-dls-low-torque-2dof": "낮은 토크 제한 DLS",
    "lab03.condition-aware-dls-high-torque-2dof": "높은 토크 제한 DLS",
    "lab03.condition-aware-dls-slow-command-2dof": "느린 명령 DLS",
    "lab03.condition-aware-dls-fast-command-2dof": "빠른 명령 DLS",
    "lab03.condition-aware-dls-low-joint-speed-2dof": "낮은 관절 속도 DLS",
    "lab03.condition-aware-dls-high-joint-speed-2dof": "높은 관절 속도 DLS",
    "lab03.condition-aware-dls-direct-retarget-2dof": "직접 재목표 DLS",
    "lab03.condition-aware-dls-inward-retarget-2dof": "안쪽 경유 재목표 DLS",
    "lab03.condition-aware-dls-fixed-speed-retarget-2dof": "고정 속도 재목표 DLS",
    "lab03.condition-aware-dls-adaptive-speed-retarget-2dof": "적응 속도 재목표 DLS",
    "lab03.interactive-2dof": "2DOF 직접 조작",
    "lab03.step": "계단 궤적",
    "lab03.trapezoidal": "사다리꼴 궤적",
    "lab03.minimum-jerk": "최소 저크 궤적",
    "lab03.s-curve": "S-커브 궤적",
    "lab03.interactive-tracking": "1D 궤적 추종",
    "lab04.neutral-hold": "중립 자세 유지",
    "lab04.neutral-hold-30s": "30초 안정성 유지",
    "lab04.joint-pd": "4번 관절 경로",
    "lab04.trajectory-tracking": "6번 관절 S-커브",
    "lab04.reach-x": "X 방향 이동",
    "lab04.cartesian-reach": "데카르트 공간 이동",
    "lab04.cartesian-soft": "부드러운 데카르트 제어",
    "lab04.cartesian-stiff": "강한 데카르트 제어",
    "lab04.interactive-cartesian-reach": "데카르트 직접 조작",
    "lab04.interactive-joint-hold": "관절 목표 직접 조작",
    "lab04.wall-soft": "부드러운 가상 벽",
    "lab04.wall-stiff": "단단한 가상 벽",
    "lab04.wall-low-damping": "낮은 벽 감쇠",
    "lab04.wall-high-damping": "높은 벽 감쇠",
    "lab04.wall-near": "가까운 가상 벽",
    "lab04.wall-far": "먼 가상 벽",
    "lab04.wall-slow-approach": "느린 벽 접근",
    "lab04.wall-fast-approach": "빠른 벽 접근",
    "lab04.wall-shallow-push": "얕은 벽 밀기",
    "lab04.wall-deep-push": "깊은 벽 밀기",
    "lab04.wall-contact-cycle": "벽 접촉 반복",
    "lab04.wall-low-retreat": "낮은 후퇴 게인",
    "lab04.wall-high-retreat": "높은 후퇴 게인",
    "lab04.interactive-virtual-wall": "가상 벽 직접 조작",
}
