model_path: models/lab01_msd/scene.xml
sim_time: 4.0
dt: 0.001
mass: 1.0
damping: 6.0
stiffness: 30.0
spring_reference: 0.0
initial_position: 0.5
initial_velocity: 0.0
force_input:
  type: step
  magnitude: 0.0
  start_time: 0.0
